" .vimrc
" Author: Rich Johnson <nixternal@gmail.com>
" Source: https://github.com/nixternal/dotfiles

" -----------------------------------------------------------------------------
" PATHOGEN & PRE-OPTIONS
" -----------------------------------------------------------------------------
filetype off
runtime bundle/vim-pathogen/autoload/pathogen.vim
silent! execute pathogen#infect()
filetype plugin indent on
set nocompatible
syntax on
" -----------------------------------------------------------------------------
" BASIC OPTIONS
" -----------------------------------------------------------------------------
set autoindent                      
set background=dark
set backspace=2
set complete=.,w,b,u,t
set completeopt=longest,menuone,preview
set confirm
set encoding=utf-8
set expandtab
set foldlevelstart=99
set foldmethod=syntax
set formatoptions-=tc
set grepprg=grep\ -nH\ $*
set guitablabel=%N/\ %t\ %M
set history=100
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set lazyredraw
set matchtime=2
set modeline
set mousehide
set nocp
set notimeout
set number
set numberwidth=1
set printoptions=header:0,duplex:long,paper:letter
set report=0
set ruler
set scrolloff=3
set shiftwidth=4
set shortmess+=a
set showcmd
set showfulltag
set showmatch
set smartcase
set softtabstop=4
set synmaxcol=800
set tabstop=4
set t_Co=256
set textwidth=80
set title
set ttimeout
set ttimeoutlen=10
set ttyfast
set vb t_vb=
set wrapscan
" -----------------------------------------------------------------------------
" WILDMENU COMPLETION
" -----------------------------------------------------------------------------
set wildmenu
set wildmenu=list:longest
set wildignore+=.hg,.git,.svn                       " version control
set wildignore+=*.aux,*.out,*.toc                   " LaTeX intermediate files
set wildignore+=*.jpg,*.bmp,*.gif,*.png,*.jpeg      " binary images
set wildignore+=*.o,*.obj,*.exe,*.dll,*.manifest    " compiled object files
set wildignore+=*.spl                               " compiled spelling word lists
set wildignore+=*.sw?                               " vim swap files
set wildignore+=*.luac                              " Lua byte code
set wildignore+=migrations                          " Django migrations
set wildignore+=*.pyc                               " Python byte code
